color: true
recursive: true
bail: false # to see which tests are failing, not just the first
require:
  - 'ts-node/register'
extension:
  - ts
ui: 'bdd'
check-leaks: true
fullStackTrace: true
# exit: true # https://github.com/Automattic/mongoose/issues/8419
timeout: 15000
